### ISSUE TITLE
CV and resume buttons are not align in mobile view

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/sabesansathananthan.github.io#10]
In about-me.html cv and resume buttons are not aligned properly align it center and make sure it is working for web view as well.

hint : `<a href="https://drive.google.com/open?id=1jhVaZfFA-IvgXUO6CCeFqLj5840V0eSr" target="_blank" class="genric-btn success circle arrow"> Download CV  &nbsp;&nbsp;<i class="fas fa-download" > </i></a>`

remove the `&nbsp;` and find a way

**Comment by jpbelo** [comment]
I can help with that. You can assign me to the issue and I’ll open PR later today.

**Comment by sabesansathananthan** [comment]
@jpbelo  Thank you.
