### ISSUE TITLE
Remove 60px padding issue.

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/sabesansathananthan.github.io#19]
> Remove the padding issue for mobile view

Also notice you get a 60px body padding on the mobile view. Not sure if that is something you purposely put there or not.

![Capture](https://user-images.githubusercontent.com/41599429/67480841-95113a80-f658-11e9-87fa-86eb3329ae12.PNG)

_Originally posted by @timd3v in https://github.com/sabesansathananthan/sabesansathananthan.github.io/issues/6#issuecomment-545872026_

**Comment by logiclrd** [comment]
I think I can do this. :-)
