### ISSUE TITLE
Adjust button position

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/sabesansathananthan.github.io#21]
in width range 768 -576 screens index.html's following buttons are not aligned with screens.
want to center the buttons in that range.

![Screenshot from 2019-10-25 00-42-56](https://user-images.githubusercontent.com/36799589/67517884-3207be00-f6c1-11e9-8659-33cdaa3d058a.png)
![Screenshot from 2019-10-25 00-43-29](https://user-images.githubusercontent.com/36799589/67517886-3207be00-f6c1-11e9-82d4-943adbc73813.png)
![Screenshot from 2019-10-25 00-44-13](https://user-images.githubusercontent.com/36799589/67517888-3207be00-f6c1-11e9-8dc0-c44c25a3ce42.png)

**Comment by logiclrd** [comment]
So the buttons with a blue background should be centered and not off on the right like that?

**Comment by sabesansathananthan** [comment]
> So the buttons with a blue background should be centered and not off on the right like that?

@logiclrd yeah, The position of the button should be in the center of the screen.

**Comment by logiclrd** [comment]
Okay :-) I'm on it.

**Comment by sabesansathananthan** [comment]
> Okay :-) I'm on it.

@logiclrd  Thank you. If you can try #10 as well this is also same problem

**Comment by logiclrd** [comment]
Looks like #10 was picked up by @jpbelo. PR for this one incoming. :-)

**Comment by sabesansathananthan** [comment]
sure. I suggest you to participate in this hackathon. main objective for these issues for this hackathon

https://hacktoberfest.digitalocean.com/details#quality-standards

**Comment by logiclrd** [comment]
That's how I found it. :-)
