### ISSUE TITLE
Suggest me a instagram widget

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/sabesansathananthan.github.io#30]
Suggest a free Insta widget to implement in the blog. Like In blog.html's Twitter implementation.

![Screenshot from 2019-10-25 10-45-06](https://user-images.githubusercontent.com/36799589/67544816-90aa5780-f714-11e9-9f27-ee979237cad9.png)

**Comment by CarolMusyoka18** [comment]
You can try some from [https://lightwidget.com/](url) or  [ https://snapwidget.com/](url)

**Comment by sabesansathananthan** [comment]
@carnationcrab  thank you

**Comment by praful-dhabekar** [comment]
To embed Instagram content you need to first visit the post on the web and get the embed code. Go to the post URL if you have it, or you can search for the username on Instagram.com, visit their profile, and then click the post to expand it. Click the more [...] button and select "Embed".

**Embed Button**

This will open a dialog where you can get the HTML embed code. Simply copy the code into your website and the embedded post will automatically load. By default the post contains the media caption. You can decide to hide it by simply unchecking the caption option in the Embed button dialog.



Embedded posts are responsive and automatically resize if the embedding container becomes smaller. This means that the content will look great both on desktop and mobile websites.
