### ISSUE TITLE
Change hover colour of social links on Contact page

### ISSUE THREAD

**Issue by shakti97** [sabesansathananthan/sabesansathananthan.github.io#31]
Right now, they are of same colour i.e. blue , its better to give them color of the social links logo

**Comment by AzimPathan** [comment]
@shakti97 I'm working on this now

**Comment by shakti97** [comment]
Go for it

**Comment by AzimPathan** [comment]
@shakti97 Please review PR #33  and add into your repo. Thanks!

**Comment by sabesansathananthan** [comment]
Finished by @AzimPathan
