### ISSUE TITLE
Youtube video is not align with mobile version

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/sabesansathananthan.github.io#4]
in https://github.com/sabesansathananthan/sabesansathananthan.github.io/blob/master/Project-Arthrocure.html  file a youtube video is not aligned with mobile browsers. want to fix
![Image from iOS (1)](https://user-images.githubusercontent.com/36799589/67458938-04852b00-f655-11e9-81a8-a41a6cea80a2.png)

**Comment by timd3v** [comment]
Hi, finding it a little hard as to what you are trying to achieve. Is this the result you are after?

![issue_01](https://user-images.githubusercontent.com/41599429/67460487-076f2400-f633-11e9-8a22-cbd5d21d0959.PNG)

**Comment by vivekgautam3** [comment]
Also there is a scroll issue due to footer 
![Screen Shot 2019-10-24 at 12 29 35 PM](https://user-images.githubusercontent.com/48016520/67461098-3220a300-f65a-11e9-8c12-6c8a760596d0.png)

**Comment by sabesansathananthan** [comment]
> Hi, finding it a little hard as to what you are trying to achieve. Is this the result you are after?
> 
> ![issue_01](https://user-images.githubusercontent.com/41599429/67460487-076f2400-f633-11e9-8a22-cbd5d21d0959.PNG)

yeah video should be fix with devices screens. this is design issue

**Comment by timd3v** [comment]
Alright here is the PR fixing the issue. #7

**Comment by sabesansathananthan** [comment]
@timd3v I merged that PR. could you find a way to fix it for web and mobile

**Comment by timd3v** [comment]
> @timd3v I merged that PR. could you find a way to fix it for web and mobile

Yeah, let me have a look.

**Comment by sabesansathananthan** [comment]
@timd3v sure, thank you

**Comment by vivekgautam3** [comment]
Add simple code in style.css

`.youtube-iframe {
	max-width: 560px;
	width: 100%;
}

.f_titlefooter {
  margin-bottom: 35px;
  display: inline-block;
}`

and simple add class 

`<iframe class="youtube-iframe" width="100%" height="315" src="https://www.youtube.com/embed/bHQitg7SEx4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

I hope this works for you.

**Comment by sabesansathananthan** [comment]
@vivekgautam3 please make a PR

**Comment by vivekgautam3** [comment]
It looks good to me

![Screen Shot 2019-10-24 at 1 48 29 PM](https://user-images.githubusercontent.com/48016520/67466607-fa6b2880-f664-11e9-9774-914f1f239a3b.png)

**Comment by sabesansathananthan** [comment]
@vivekgautam3  could you please sent your code snapshot.

**Comment by sabesansathananthan** [comment]
@vivekgautam3 
![Screenshot from 2019-10-24 13-53-51](https://user-images.githubusercontent.com/36799589/67467142-df4ce880-f665-11e9-9f44-21432331cacc.png)

**Comment by timd3v** [comment]
Made a new PR check it out. #8

**Comment by sabesansathananthan** [comment]
@timd3v resolve conflicts

**Comment by timd3v** [comment]
If you want a little more space for the video to breath.

![Capture](https://user-images.githubusercontent.com/41599429/67468636-c41cb180-f642-11e9-83c3-dfa1127b75d0.PNG)
