### ISSUE TITLE
footer part is not aligned with mobile phones

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/sabesansathananthan.github.io#6]
In each files footer part is not aligned with mobile phones that black color should extend until the bottom of the site 
![Image from iOS (2)](https://user-images.githubusercontent.com/36799589/67459472-4c588200-f656-11e9-9851-da57e7547ed6.png)

**Comment by vivekgautam3** [comment]
Move height **350px to auto**

.footer_area {
    background: #000410;
    height:350px;
![Screen Shot 2019-10-24 at 1 52 36 PM](https://user-images.githubusercontent.com/48016520/67466947-8c733100-f665-11e9-97e8-2112d8c23863.png)

}

**Comment by timd3v** [comment]
> thank you @vivekgautam3 @timd3v but Can I reduce the web view height???

Not totally sure what you mean by that. Could you clarify?

**Comment by sabesansathananthan** [comment]
@vivekgautam3 please make a Pull request for other open-source repos as well.
I suggest you to participate in this hackathon

https://hacktoberfest.digitalocean.com/details#quality-standards

**Comment by timd3v** [comment]
I see, yeah you have a .p_120 class attached to the footer, increasing its padding by 120px. I will create a PR in a sec with the fix.

**Comment by timd3v** [comment]
Hopefully you can adjust the height to your preference or leave it as it is. #11

**Comment by timd3v** [comment]
> Hopefully you can adjust the height to your preference or leave it as it is. #11

Also notice you get a 60px body padding on the mobile view. Not sure if that is something you purposely put there or not.

![Capture](https://user-images.githubusercontent.com/41599429/67480841-95113a80-f658-11e9-87fa-86eb3329ae12.PNG)

**Comment by sabesansathananthan** [comment]
@timd3v shall we remove it
