### ISSUE TITLE
design issue in blog area

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/sabesansathananthan.github.io#9]
In blog.html there was a design issue and want to fix it. 
![Image from iOS](https://user-images.githubusercontent.com/36799589/67477505-d8c76c80-f677-11e9-842e-5b329b5d4b98.png)

**Comment by WillyFerry** [comment]
can i solved this?

**Comment by WillyFerry** [comment]
i mean work on your problem

**Comment by sabesansathananthan** [comment]
sure. Thank you.
